### ISSUE TITLE
Installation - Some NPM Warnings

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [puikinsh/Adminator-admin-dashboard#36] opened 2018-01-20 17:04 UTC
I just installed as the readme file says and when I ran `npm install` started with this:

    npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
    npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
    npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

This is not a bug, and if I knew how to resolve it I'd do it.

**Comment by AndreiCN** [comment] 2018-02-02 16:11
What version of node do you have ? Please make sure that you have the latest one. Also if you have no further questions or if you solved it in the meantime please close the ticket, thank you !

**Comment by MikeVelazcoMtz** [comment] 2018-02-02 17:40
Please correct me if I'm wrong, but what I understood from the messages is that some packages in the `package.json` are deprecated and it's recommended to update or use another alternative.

Then, the version of node wouldn't be a problem, but when I installed node I got the latest stable version.

**Comment by krzysiekpiasecki** [comment] 2018-02-09 20:13
@MikeVelazcoMtz 

> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 

After merging #48 this warning will disappear.

> npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

After merging https://github.com/kevva/gulp-decompress/pull/13 this warning also will disappear. This warning is caused by the libraries which uses a deprecated gulp-util.

> npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.

As written. To remove this warning this project should migrate to jqvmap. Probably there are no plans to change this plugin.

If your questions are resolved, then please close this ticket.

**Closed as completed** 2018-02-09 21:00 UTC
Labels: help wanted

**Comment by atlasmoon** [comment] 2019-05-27 10:50
HI team
I confirm NPM Warning

npm install
npm WARN deprecated jvectormap@2.0.4: jvectormap is not maintened since Aug 2015. You can use jvectormap-next or jqvmap instead.
npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
loadDep:ware → resolveWit ▄ 
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
loadDep:yargs → resolveWi ▀ 
npm WARN prefer global node-gyp@3.8.0 should be installed with -g
