### ISSUE TITLE
Fonts are not loaded when the project is builded

### ISSUE THREAD

**Issue by JiProchazka** [puikinsh/Adminator-admin-dashboard#35] opened 2018-01-17 23:59 UTC
Hi,

when I run `npm run build` the fonts are placed to the root (would be nice if they would be placed under `assets/static/fonts`), but mainly they are not getting loaded. I'm getting:

    vendor.js:1 GET file:///af7ae505a9eed503f8b8e6982036873e.woff2 net::ERR_FILE_NOT_FOUND
    vendor.js:1 GET file:///a1ecc3b826d01251edddf29c3e4e1e97.woff net::ERR_FILE_NOT_FOUND
    index.html:1 GET file:///fee66e712a8a08eef5805a46892932ad.woff net::ERR_FILE_NOT_FOUND
    index.html:1 GET file:///e23a7dcaefbde4e74e263247aa42ecd7.ttf net::ERR_FILE_NOT_FOUND
    index.html:1 GET file:///b06871f281fee6b241d60582ae9369b9.ttf net::ERR_FILE_NOT_FOUND

Any idea how to fix this?

Thanks

**Comment by kevinrjn** [comment] 2018-01-22 12:28
Same problem. I'm trying to integrate this template into an angular project but fonts having to be in the root folder is a big issue. Someone here to help us please ? Thanks

**Comment by acsel31** [comment] 2018-01-26 18:24
Find in result js files (vendor.js and bundle.js) next code:
t.exports=a.p+"a1ecc3b826d01251edddf29c3e4e1e97.woff"
and replace it as you need (delete a.p and write your path)
In my case a.p=="/" and i have no symbols.
Maybe, this option can configured in building files, but i don't known
Sorry, i not speak english.

Oh, in file  webpack/config.js:
publicPath: 'your path to files', default is '/'

**Comment by jepperaskdk** [comment] 2018-01-27 15:06
Try updating `webpack/rules/fonts.js` to the following. Update outputPath as you wish and it should be reflected in bundle.js.

```
module.exports = {
  test: /\.(eot|svg|ttf|woff|woff2)$/,
  exclude : /(node_modules)/,
  loader: 'file-loader',
  options: {
    outputPath: 'assets/fonts/',
  },
};
```

**Comment by AndreiCN** [comment] 2018-02-02 16:14
@JiProchazka did you find a solution for this in the meantime ?

**Comment by krzysiekpiasecki** [comment] 2018-02-09 22:24
@JiProchazka Can't reproduce. Still got the problem?

**Comment by anzolin** [comment] 2018-02-15 11:34
@JiProchazka what happened to you happened to me and if you do as @acsel31 said, you will succeed. **If you want, I can pass the changed files to you.**

**Comment by krzysiekpiasecki** [comment] 2018-02-18 12:09
@AndreiCN Did you reproduce this defect? See also the latest deploy http://adminator.surge.sh/index.html. No problem with fonts.

**Comment by krzysiekpiasecki** [comment] 2018-05-10 20:53
@AndreiCN @JiProchazka is no more active on this issue. I propose to close this issue.

**Comment by krzysiekpiasecki** [comment] 2019-05-10 13:30
Close due to inactivity

**Closed as completed by krzysiekpiasecki** 2019-05-10 13:30 UTC
Labels: help wanted

**Comment by jrichardsz** [comment] 2020-09-16 23:03
If I create a new html inside a folder I get the same error

![https://i.ibb.co/mhC8fm8/error.png](https://i.ibb.co/mhC8fm8/error.png)

Inspecting , I see that font is loaded from:

http://localhost:8080/settings/a1ecc3b826d01251edddf29c3e4e1e97.woff

Due to my url http://localhost:8080/settings/page

I fixed it, following the @acsel31  workaround:

replace in bundle.js
a.p+"a1ecc3b826d01251edddf29c3e4e1e97.woff"
to
"/a1ecc3b826d01251edddf29c3e4e1e97.woff"

Is the another more elegant way to fix this?
